version: '3.2'

services:
  base-api:
    image: base-api
    build:
      context: base-api/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  base-api-test:
    image: base-api-test
    build:
      context: .
      dockerfile: base-api.Tests/Dockerfile
