version: '3.2'

services:
  mat-process-api:
    image: mat-process-api
    build:
      context: mat-process-api/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  mat-process-api-test:
    image: mat-process-api-test
    build:
      context: .
      dockerfile: mat-process-api.Tests/Dockerfile
    environment:
        - MONGO_CONN_STRING=mongodb://mongo-db:27017/?gssapiServiceName=mongodb
    links:
      - mongo-db
  mongo-db:
    image: mongo:3.6
    ports:
      - 1433:27017

