version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-cli: circleci/aws-cli@0.1.9

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: build
          command: docker-compose build base-api-test
      - run:
          name: Run tests
          command: docker-compose up base-api-test

workflows:
  check-and-deploy:
      jobs:
      - build-and-test
